export const PRODUCT_CATEOGRY_LIST_REQUEST = 'PRODUCT_CATEOGRY_LIST_REQUEST';
export const PRODUCT_CATEOGRY_LIST_SUCCESS = 'PRODUCT_CATEOGRY_LIST_SUCCESS';
export const PRODUCT_CATEOGRY_LIST_FAILURE = 'PRODUCT_CATEOGRY_LIST_FAILURE';
export type PRODUCT_CATEOGRY_LIST_REQUEST = typeof PRODUCT_CATEOGRY_LIST_REQUEST;
export type PRODUCT_CATEOGRY_LIST_SUCCESS = typeof PRODUCT_CATEOGRY_LIST_SUCCESS;
export type PRODUCT_CATEOGRY_LIST_FAILURE = typeof PRODUCT_CATEOGRY_LIST_FAILURE;

export const DICT_LIST_REQUEST = 'DICT_LIST_REQUEST';
export const DICT_LIST_SUCCESS = 'DICT_LIST_SUCCESS';
export const DICT_LIST_FAILURE = 'DICT_LIST_FAILURE';
export type DICT_LIST_REQUEST = typeof DICT_LIST_REQUEST;
export type DICT_LIST_SUCCESS = typeof DICT_LIST_SUCCESS;
export type DICT_LIST_FAILURE = typeof DICT_LIST_FAILURE;

export const DICT_LIST_ALL_REQUEST = 'DICT_LIST_ALL_REQUEST';
export const DICT_LIST_ALL_SUCCESS = 'DICT_LIST_ALL_SUCCESS';
export const DICT_LIST_ALL_FAILURE = 'DICT_LIST_ALL_FAILURE';
export type DICT_LIST_ALL_REQUEST = typeof DICT_LIST_ALL_REQUEST;
export type DICT_LIST_ALL_SUCCESS = typeof DICT_LIST_ALL_SUCCESS;
export type DICT_LIST_ALL_FAILURE = typeof DICT_LIST_ALL_FAILURE;

export const COMPANY_ALL_REQUEST = 'COMPANY_ALL_REQUEST';
export const COMPANY_ALL_SUCCESS = 'COMPANY_ALL_SUCCESS';
export const COMPANY_ALL_FAILURE = 'COMPANY_ALL_FAILURE';
export type COMPANY_ALL_REQUEST = typeof COMPANY_ALL_REQUEST;
export type COMPANY_ALL_SUCCESS = typeof COMPANY_ALL_SUCCESS;
export type COMPANY_ALL_FAILURE = typeof COMPANY_ALL_FAILURE;

export const CHANNEL_ALL_REQUEST = 'CHANNEL_ALL_REQUEST';
export const CHANNEL_ALL_SUCCESS = 'CHANNEL_ALL_SUCCESS';
export const CHANNEL_ALL_FAILURE = 'CHANNEL_ALL_FAILURE';
export type CHANNEL_ALL_REQUEST = typeof CHANNEL_ALL_REQUEST;
export type CHANNEL_ALL_SUCCESS = typeof CHANNEL_ALL_SUCCESS;
export type CHANNEL_ALL_FAILURE = typeof CHANNEL_ALL_FAILURE;

export const CHANNEL_GROUP_ALL_REQUEST = 'CHANNEL_GROUP_ALL_REQUEST';
export const CHANNEL_GROUP_ALL_SUCCESS = 'CHANNEL_GROUP_ALL_SUCCESS';
export const CHANNEL_GROUP_ALL_FAILURE = 'CHANNEL_GROUP_ALL_FAILURE';
export type CHANNEL_GROUP_ALL_REQUEST = typeof CHANNEL_GROUP_ALL_REQUEST;
export type CHANNEL_GROUP_ALL_SUCCESS = typeof CHANNEL_GROUP_ALL_SUCCESS;
export type CHANNEL_GROUP_ALL_FAILURE = typeof CHANNEL_GROUP_ALL_FAILURE;

export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST';
export const PRODUCT_ALL_SUCCESS = 'PRODUCT_ALL_SUCCESS';
export const PRODUCT_ALL_FAILURE = 'PRODUCT_ALL_FAILURE';
export type PRODUCT_ALL_REQUEST = typeof PRODUCT_ALL_REQUEST;
export type PRODUCT_ALL_SUCCESS = typeof PRODUCT_ALL_SUCCESS;
export type PRODUCT_ALL_FAILURE = typeof PRODUCT_ALL_FAILURE;

export const PRODUCT_CHANNEL_ALL_REQUEST = 'PRODUCT_CHANNEL_ALL_REQUEST';
export const PRODUCT_CHANNEL_ALL_SUCCESS = 'PRODUCT_CHANNEL_ALL_SUCCESS';
export const PRODUCT_CHANNEL_ALL_FAILURE = 'PRODUCT_CHANNEL_ALL_FAILURE';
export type PRODUCT_CHANNEL_ALL_REQUEST = typeof PRODUCT_CHANNEL_ALL_REQUEST;
export type PRODUCT_CHANNEL_ALL_SUCCESS = typeof PRODUCT_CHANNEL_ALL_SUCCESS;
export type PRODUCT_CHANNEL_ALL_FAILURE = typeof PRODUCT_CHANNEL_ALL_FAILURE;

export const COMPANY_CHANNEL_ALL_REQUEST = 'COMPANY_CHANNEL_ALL_REQUEST';
export const COMPANY_CHANNEL_ALL_SUCCESS = 'COMPANY_CHANNEL_ALL_SUCCESS';
export const COMPANY_CHANNEL_ALL_FAILURE = 'COMPANY_CHANNEL_ALL_FAILURE';
export type COMPANY_CHANNEL_ALL_REQUEST = typeof COMPANY_CHANNEL_ALL_REQUEST;
export type COMPANY_CHANNEL_ALL_SUCCESS = typeof COMPANY_CHANNEL_ALL_SUCCESS;
export type COMPANY_CHANNEL_ALL_FAILURE = typeof COMPANY_CHANNEL_ALL_FAILURE;

export const PRODUCT_ALL_BY_COMPANY_REQUEST = 'PRODUCT_ALL_BY_COMPANY_REQUEST';
export const PRODUCT_ALL_BY_COMPANY_SUCCESS = 'PRODUCT_ALL_BY_COMPANY_SUCCESS';
export const PRODUCT_ALL_BY_COMPANY_FAILURE = 'PRODUCT_ALL_BY_COMPANY_FAILURE';
export type PRODUCT_ALL_BY_COMPANY_REQUEST = typeof PRODUCT_ALL_BY_COMPANY_REQUEST;
export type PRODUCT_ALL_BY_COMPANY_SUCCESS = typeof PRODUCT_ALL_BY_COMPANY_SUCCESS;
export type PRODUCT_ALL_BY_COMPANY_FAILURE = typeof PRODUCT_ALL_BY_COMPANY_FAILURE;

export const CHANNEL_ALL_BY_PRODUCT_REQUEST = 'CHANNEL_ALL_BY_PRODUCT_REQUEST';
export const CHANNEL_ALL_BY_PRODUCT_SUCCESS = 'CHANNEL_ALL_BY_PRODUCT_SUCCESS';
export const CHANNEL_ALL_BY_PRODUCT_FAILURE = 'CHANNEL_ALL_BY_PRODUCT_FAILURE';
export type CHANNEL_ALL_BY_PRODUCT_REQUEST = typeof CHANNEL_ALL_BY_PRODUCT_REQUEST;
export type CHANNEL_ALL_BY_PRODUCT_SUCCESS = typeof CHANNEL_ALL_BY_PRODUCT_SUCCESS;
export type CHANNEL_ALL_BY_PRODUCT_FAILURE = typeof CHANNEL_ALL_BY_PRODUCT_FAILURE;

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export type CHANGE_LOADING_STATUS = typeof CHANGE_LOADING_STATUS;

export const GET_CHANNEL_INFO_REQUEST = 'GET_CHANNEL_INFO_REQUEST';
export const GET_CHANNEL_INFO_SUCCESS = 'GET_CHANNEL_INFO_SUCCESS';
export const GET_CHANNEL_INFO_FAILURE = 'GET_CHANNEL_INFO_FAILURE';
export type GET_CHANNEL_INFO_REQUEST = typeof GET_CHANNEL_INFO_REQUEST;
export type GET_CHANNEL_INFO_SUCCESS = typeof GET_CHANNEL_INFO_SUCCESS;
export type GET_CHANNEL_INFO_FAILURE = typeof GET_CHANNEL_INFO_FAILURE;

export const PLAN_AND_POLICY_TYPE_BY_PRODUCT_REQUEST = 'PLAN_AND_POLICY_TYPE_BY_PRODUCT_REQUEST';
export const PLAN_AND_POLICY_TYPE_BY_PRODUCT_SUCCESS = 'PLAN_AND_POLICY_TYPE_BY_PRODUCT_SUCCESS';
export const PLAN_AND_POLICY_TYPE_BY_PRODUCT_FAILURE = 'PLAN_AND_POLICY_TYPE_BY_PRODUCT_FAILURE';
export type PLAN_AND_POLICY_TYPE_BY_PRODUCT_REQUEST = typeof PLAN_AND_POLICY_TYPE_BY_PRODUCT_REQUEST;
export type PLAN_AND_POLICY_TYPE_BY_PRODUCT_SUCCESS = typeof PLAN_AND_POLICY_TYPE_BY_PRODUCT_SUCCESS;
export type PLAN_AND_POLICY_TYPE_BY_PRODUCT_FAILURE = typeof PLAN_AND_POLICY_TYPE_BY_PRODUCT_FAILURE;

export const PRODUCT_LIST_BY_LOGINID_REQUEST = 'PRODUCT_LIST_BY_LOGINID_REQUEST';
export const PRODUCT_LIST_BY_LOGINID_SUCCESS = 'PRODUCT_LIST_BY_LOGINID_SUCCESS';
export const PRODUCT_LIST_BY_LOGINID_FAILURE = 'PRODUCT_LIST_BY_LOGINID_FAILURE';
export type PRODUCT_LIST_BY_LOGINID_REQUEST = typeof PRODUCT_LIST_BY_LOGINID_REQUEST;
export type PRODUCT_LIST_BY_LOGINID_SUCCESS = typeof PRODUCT_LIST_BY_LOGINID_SUCCESS;
export type PRODUCT_LIST_BY_LOGINID_FAILURE = typeof PRODUCT_LIST_BY_LOGINID_FAILURE;

export const CHANNEL_REQUEST = 'CHANNEL_REQUEST';
export const CHANNEL_SUCCESS = 'CHANNEL_SUCCESS';
export const CHANNEL_FAILURE = 'CHANNEL_FAILURE';
export type CHANNEL_REQUEST = typeof CHANNEL_REQUEST;
export type CHANNEL_SUCCESS = typeof CHANNEL_SUCCESS;
export type CHANNEL_FAILURE = typeof CHANNEL_FAILURE;

export const CHANNEL_ADDORMODIFY_REQUEST = 'CHANNEL_ADDORMODIFY_REQUEST';
export const CHANNEL_ADDORMODIFY_SUCCESS = 'CHANNEL_ADDORMODIFY_SUCCESS';
export const CHANNEL_ADDORMODIFY_FAILURE = 'CHANNEL_ADDORMODIFY_FAILURE';
export type CHANNEL_ADDORMODIFY_REQUEST = typeof CHANNEL_ADDORMODIFY_REQUEST;
export type CHANNEL_ADDORMODIFY_SUCCESS = typeof CHANNEL_ADDORMODIFY_SUCCESS;
export type CHANNEL_ADDORMODIFY_FAILURE = typeof CHANNEL_ADDORMODIFY_FAILURE;

export const CHANNEL_ADD_REQUEST = 'CHANNEL_ADD_REQUEST';
export const CHANNEL_ADD_SUCCESS = 'CHANNEL_ADD_SUCCESS';
export const CHANNEL_ADD_FAILURE = 'CHANNEL_ADD_FAILURE';
export type CHANNEL_ADD_REQUEST = typeof CHANNEL_ADD_REQUEST;
export type CHANNEL_ADD_SUCCESS = typeof CHANNEL_ADD_SUCCESS;
export type CHANNEL_ADD_FAILURE = typeof CHANNEL_ADD_FAILURE;

export const CHANNEL_MODIFY_REQUEST = 'CHANNEL_MODIFY_REQUEST';
export const CHANNEL_MODIFY_SUCCESS = 'CHANNEL_MODIFY_SUCCESS';
export const CHANNEL_MODIFY_FAILURE = 'CHANNEL_MODIFY_FAILURE';
export type CHANNEL_MODIFY_REQUEST = typeof CHANNEL_MODIFY_REQUEST;
export type CHANNEL_MODIFY_SUCCESS = typeof CHANNEL_MODIFY_SUCCESS;
export type CHANNEL_MODIFY_FAILURE = typeof CHANNEL_MODIFY_FAILURE;

export const CHANNEL_DETAIL_REQUEST = 'CHANNEL_DETAIL_REQUEST';
export const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
export const CHANNEL_DETAIL_FAILURE = 'CHANNEL_DETAIL_FAILURE';
export type CHANNEL_DETAIL_REQUEST = typeof CHANNEL_DETAIL_REQUEST;
export type CHANNEL_DETAIL_SUCCESS = typeof CHANNEL_DETAIL_SUCCESS;
export type CHANNEL_DETAIL_FAILURE = typeof CHANNEL_DETAIL_FAILURE;

export const CHANNEL_SHOW_KEY = 'CHANNEL_SHOW_KEY';
export type CHANNEL_SHOW_KEY = typeof CHANNEL_SHOW_KEY;

export const CHANNEL_UPDATE_SECRETKEY_REQUEST = 'CHANNEL_UPDATE_SECRETKEY_REQUEST';
export const CHANNEL_UPDATE_SECRETKEY_SUCCESS = 'CHANNEL_UPDATE_SECRETKEY_SUCCESS';
export const CHANNEL_UPDATE_SECRETKEY_FAILURE = 'CHANNEL_UPDATE_SECRETKEY_FAILURE';
export type CHANNEL_UPDATE_SECRETKEY_REQUEST = typeof CHANNEL_UPDATE_SECRETKEY_REQUEST;
export type CHANNEL_UPDATE_SECRETKEY_SUCCESS = typeof CHANNEL_UPDATE_SECRETKEY_SUCCESS;
export type CHANNEL_UPDATE_SECRETKEY_FAILURE = typeof CHANNEL_UPDATE_SECRETKEY_FAILURE;

export const CHANNEL_UPDATE_STATUS_REQUEST = 'CHANNEL_UPDATE_STATUS_REQUEST';
export const CHANNEL_UPDATE_STATUS_SUCCESS = 'CHANNEL_UPDATE_STATUS_SUCCESS';
export const CHANNEL_UPDATE_STATUS_FAILURE = 'CHANNEL_UPDATE_STATUS_FAILURE';
export type CHANNEL_UPDATE_STATUS_REQUEST = typeof CHANNEL_UPDATE_STATUS_REQUEST;
export type CHANNEL_UPDATE_STATUS_SUCCESS = typeof CHANNEL_UPDATE_STATUS_SUCCESS;
export type CHANNEL_UPDATE_STATUS_FAILURE = typeof CHANNEL_UPDATE_STATUS_FAILURE;

export const CHANNEL_SET_EXPANDED_ROWKEYS = 'CHANNEL_SET_EXPANDED_ROWKEYS';
export type CHANNEL_SET_EXPANDED_ROWKEYS = typeof CHANNEL_SET_EXPANDED_ROWKEYS;

export const CHANNEL_SUB_LIST_REQUEST = 'CHANNEL_SUB_LIST_REQUEST';
export const CHANNEL_SUB_LIST_SUCCESS = 'CHANNEL_SUB_LIST_SUCCESS';
export const CHANNEL_SUB_LIST_FAILURE = 'CHANNEL_SUB_LIST_FAILURE';
export type CHANNEL_SUB_LIST_REQUEST = typeof CHANNEL_SUB_LIST_REQUEST;
export type CHANNEL_SUB_LIST_SUCCESS = typeof CHANNEL_SUB_LIST_SUCCESS;
export type CHANNEL_SUB_LIST_FAILURE = typeof CHANNEL_SUB_LIST_FAILURE;

export const SET_SUB_CHANNEL_LIST_PAGE = 'SET_SUB_CHANNEL_LIST_PAGE';
export type SET_SUB_CHANNEL_LIST_PAGE = typeof SET_SUB_CHANNEL_LIST_PAGE;

export const PRODUCT_SHOW_KEY = 'PRODUCT_SHOW_KEY';
export type PRODUCT_SHOW_KEY = typeof PRODUCT_SHOW_KEY;

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';
export type PRODUCT_REQUEST = typeof PRODUCT_REQUEST;
export type PRODUCT_SUCCESS = typeof PRODUCT_SUCCESS;
export type PRODUCT_FAILURE = typeof PRODUCT_FAILURE;

export const PRODUCT_ADDORMODIFY_REQUEST = 'PRODUCT_ADDORMODIFY_REQUEST';
export const PRODUCT_ADDORMODIFY_SUCCESS = 'PRODUCT_ADDORMODIFY_SUCCESS';
export const PRODUCT_ADDORMODIFY_FAILURE = 'PRODUCT_ADDORMODIFY_FAILURE';
export type PRODUCT_ADDORMODIFY_REQUEST = typeof PRODUCT_ADDORMODIFY_REQUEST;
export type PRODUCT_ADDORMODIFY_SUCCESS = typeof PRODUCT_ADDORMODIFY_SUCCESS;
export type PRODUCT_ADDORMODIFY_FAILURE = typeof PRODUCT_ADDORMODIFY_FAILURE;

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAILURE = 'PRODUCT_DETAIL_FAILURE';
export type PRODUCT_DETAIL_REQUEST = typeof PRODUCT_DETAIL_REQUEST;
export type PRODUCT_DETAIL_SUCCESS = typeof PRODUCT_DETAIL_SUCCESS;
export type PRODUCT_DETAIL_FAILURE = typeof PRODUCT_DETAIL_FAILURE;

export const PRODUCT_EDITOR_DETAIL_REQUEST = 'PRODUCT_EDITOR_DETAIL_REQUEST';
export const PRODUCT_EDITOR_DETAIL_SUCCESS = 'PRODUCT_EDITOR_DETAIL_SUCCESS';
export const PRODUCT_EDITOR_DETAIL_FAILURE = 'PRODUCT_EDITOR_DETAIL_FAILURE';
export type PRODUCT_EDITOR_DETAIL_REQUEST = typeof PRODUCT_EDITOR_DETAIL_REQUEST;
export type PRODUCT_EDITOR_DETAIL_SUCCESS = typeof PRODUCT_EDITOR_DETAIL_SUCCESS;
export type PRODUCT_EDITOR_DETAIL_FAILURE = typeof PRODUCT_EDITOR_DETAIL_FAILURE;

export const PRODUCT_COMPANY_VISIBLE = 'PRODUCT_COMPANY_VISIBLE';
export type PRODUCT_COMPANY_VISIBLE = typeof PRODUCT_COMPANY_VISIBLE;

export const PRODUCT_UPDATE_STATUS_REQUEST = 'PRODUCT_UPDATE_STATUS_REQUEST';
export const PRODUCT_UPDATE_STATUS_SUCCESS = 'PRODUCT_UPDATE_STATUS_SUCCESS';
export const PRODUCT_UPDATE_STATUS_FAILURE = 'PRODUCT_UPDATE_STATUS_FAILURE';
export type PRODUCT_UPDATE_STATUS_REQUEST = typeof PRODUCT_UPDATE_STATUS_REQUEST;
export type PRODUCT_UPDATE_STATUS_SUCCESS = typeof PRODUCT_UPDATE_STATUS_SUCCESS;
export type PRODUCT_UPDATE_STATUS_FAILURE = typeof PRODUCT_UPDATE_STATUS_FAILURE;

export const PRODUCT_UPDATE_HTML_REQUEST = 'PRODUCT_UPDATE_HTML_REQUEST';
export const PRODUCT_UPDATE_HTML_SUCCESS = 'PRODUCT_UPDATE_HTML_SUCCESS';
export const PRODUCT_UPDATE_HTML_FAILURE = 'PRODUCT_UPDATE_HTML_FAILURE';
export type PRODUCT_UPDATE_HTML_REQUEST = typeof PRODUCT_UPDATE_HTML_REQUEST;
export type PRODUCT_UPDATE_HTML_SUCCESS = typeof PRODUCT_UPDATE_HTML_SUCCESS;
export type PRODUCT_UPDATE_HTML_FAILURE = typeof PRODUCT_UPDATE_HTML_FAILURE;

export const PRODUCT_COMPANY_ALL_REQUEST = 'PRODUCT_COMPANY_ALL_REQUEST';
export const PRODUCT_COMPANY_ALL_SUCCESS = 'PRODUCT_COMPANY_ALL_SUCCESS';
export const PRODUCT_COMPANY_ALL_FAILURE = 'PRODUCT_COMPANY_ALL_FAILURE';
export type PRODUCT_COMPANY_ALL_REQUEST = typeof PRODUCT_COMPANY_ALL_REQUEST;
export type PRODUCT_COMPANY_ALL_SUCCESS = typeof PRODUCT_COMPANY_ALL_SUCCESS;
export type PRODUCT_COMPANY_ALL_FAILURE = typeof PRODUCT_COMPANY_ALL_FAILURE;

export const PRODUCT_PREVIEW_VISIBLE = 'PRODUCT_PREVIEW_VISIBLE';
export type PRODUCT_PREVIEW_VISIBLE = typeof PRODUCT_PREVIEW_VISIBLE;

export const POLICY_SHOW_KEY = 'POLICY_SHOW_KEY';
export type POLICY_SHOW_KEY = typeof POLICY_SHOW_KEY;

export const POLICY_REQUEST = 'POLICY_REQUEST';
export const POLICY_SUCCESS = 'POLICY_SUCCESS';
export const POLICY_FAILURE = 'POLICY_FAILURE';
export type POLICY_REQUEST = typeof POLICY_REQUEST;
export type POLICY_SUCCESS = typeof POLICY_SUCCESS;
export type POLICY_FAILURE = typeof POLICY_FAILURE;

export const POLICY_DETAIL_REQUEST = 'POLICY_DETAIL_REQUEST';
export const POLICY_DETAIL_SUCCESS = 'POLICY_DETAIL_SUCCESS';
export const POLICY_DETAIL_FAILURE = 'POLICY_DETAIL_FAILURE';
export type POLICY_DETAIL_REQUEST = typeof POLICY_DETAIL_REQUEST;
export type POLICY_DETAIL_SUCCESS = typeof POLICY_DETAIL_SUCCESS;
export type POLICY_DETAIL_FAILURE = typeof POLICY_DETAIL_FAILURE;

export const POLICY_DETAIL_APPLI_REQUEST = 'POLICY_DETAIL_APPLI_REQUEST';
export const POLICY_DETAIL_APPLI_SUCCESS = 'POLICY_DETAIL_APPLI_SUCCESS';
export const POLICY_DETAIL_APPLI_FAILURE = 'POLICY_DETAIL_APPLI_FAILURE';
export type POLICY_DETAIL_APPLI_REQUEST = typeof POLICY_DETAIL_APPLI_REQUEST;
export type POLICY_DETAIL_APPLI_SUCCESS = typeof POLICY_DETAIL_APPLI_SUCCESS;
export type POLICY_DETAIL_APPLI_FAILURE = typeof POLICY_DETAIL_APPLI_FAILURE;

export const POLICY_DETAIL_FAVOREE_REQUEST = 'POLICY_DETAIL_FAVOREE_REQUEST';
export const POLICY_DETAIL_FAVOREE_SUCCESS = 'POLICY_DETAIL_FAVOREE_SUCCESS';
export const POLICY_DETAIL_FAVOREE_FAILURE = 'POLICY_DETAIL_FAVOREE_FAILURE';
export type POLICY_DETAIL_FAVOREE_REQUEST = typeof POLICY_DETAIL_FAVOREE_REQUEST;
export type POLICY_DETAIL_FAVOREE_SUCCESS = typeof POLICY_DETAIL_FAVOREE_SUCCESS;
export type POLICY_DETAIL_FAVOREE_FAILURE = typeof POLICY_DETAIL_FAVOREE_FAILURE;

export const POLICY_DETAIL_RECOGNIZEE_REQUEST = 'POLICY_DETAIL_RECOGNIZEE_REQUEST';
export const POLICY_DETAIL_RECOGNIZEE_SUCCESS = 'POLICY_DETAIL_RECOGNIZEE_SUCCESS';
export const POLICY_DETAIL_RECOGNIZEE_FAILURE = 'POLICY_DETAIL_RECOGNIZEE_FAILURE';
export type POLICY_DETAIL_RECOGNIZEE_REQUEST = typeof POLICY_DETAIL_RECOGNIZEE_REQUEST;
export type POLICY_DETAIL_RECOGNIZEE_SUCCESS = typeof POLICY_DETAIL_RECOGNIZEE_SUCCESS;
export type POLICY_DETAIL_RECOGNIZEE_FAILURE = typeof POLICY_DETAIL_RECOGNIZEE_FAILURE;

export const POLICY_DETAIL_FEE_REQUEST = 'POLICY_DETAIL_FEE_REQUEST';
export const POLICY_DETAIL_FEE_SUCCESS = 'POLICY_DETAIL_FEE_SUCCESS';
export const POLICY_DETAIL_FEE_FAILURE = 'POLICY_DETAIL_FEE_FAILURE';
export type POLICY_DETAIL_FEE_REQUEST = typeof POLICY_DETAIL_FEE_REQUEST;
export type POLICY_DETAIL_FEE_SUCCESS = typeof POLICY_DETAIL_FEE_SUCCESS;
export type POLICY_DETAIL_FEE_FAILURE = typeof POLICY_DETAIL_FEE_FAILURE;

export const POLICY_DETAIL_PAY_REQUEST = 'POLICY_DETAIL_PAY_REQUEST';
export const POLICY_DETAIL_PAY_SUCCESS = 'POLICY_DETAIL_PAY_SUCCESS';
export const POLICY_DETAIL_PAY_FAILURE = 'POLICY_DETAIL_PAY_FAILURE';
export type POLICY_DETAIL_PAY_REQUEST = typeof POLICY_DETAIL_PAY_REQUEST;
export type POLICY_DETAIL_PAY_SUCCESS = typeof POLICY_DETAIL_PAY_SUCCESS;
export type POLICY_DETAIL_PAY_FAILURE = typeof POLICY_DETAIL_PAY_FAILURE;

export const POLICY_DETAIL_PAY_LIST_REQUEST = 'POLICY_DETAIL_PAY_LIST_REQUEST';
export const POLICY_DETAIL_PAY_LIST_SUCCESS = 'POLICY_DETAIL_PAY_LIST_SUCCESS';
export const POLICY_DETAIL_PAY_LIST_FAILURE = 'POLICY_DETAIL_PAY_LIST_FAILURE';
export type POLICY_DETAIL_PAY_LIST_REQUEST = typeof POLICY_DETAIL_PAY_LIST_REQUEST;
export type POLICY_DETAIL_PAY_LIST_SUCCESS = typeof POLICY_DETAIL_PAY_LIST_SUCCESS;
export type POLICY_DETAIL_PAY_LIST_FAILURE = typeof POLICY_DETAIL_PAY_LIST_FAILURE;

export const POLICY_DETAIL_CLAUSE_REQUEST = 'POLICY_DETAIL_CLAUSE_REQUEST';
export const POLICY_DETAIL_CLAUSE_SUCCESS = 'POLICY_DETAIL_CLAUSE_SUCCESS';
export const POLICY_DETAIL_CLAUSE_FAILURE = 'POLICY_DETAIL_CLAUSE_FAILURE';
export type POLICY_DETAIL_CLAUSE_REQUEST = typeof POLICY_DETAIL_CLAUSE_REQUEST;
export type POLICY_DETAIL_CLAUSE_SUCCESS = typeof POLICY_DETAIL_CLAUSE_SUCCESS;
export type POLICY_DETAIL_CLAUSE_FAILURE = typeof POLICY_DETAIL_CLAUSE_FAILURE;

export const POLICY_DETAIL_BASE_REQUEST = 'POLICY_DETAIL_BASE_REQUEST';
export const POLICY_DETAIL_BASE_SUCCESS = 'POLICY_DETAIL_BASE_SUCCESS';
export const POLICY_DETAIL_BASE_FAILURE = 'POLICY_DETAIL_BASE_FAILURE';
export type POLICY_DETAIL_BASE_REQUEST = typeof POLICY_DETAIL_BASE_REQUEST;
export type POLICY_DETAIL_BASE_SUCCESS = typeof POLICY_DETAIL_BASE_SUCCESS;
export type POLICY_DETAIL_BASE_FAILURE = typeof POLICY_DETAIL_BASE_FAILURE;

export const POLICY_DETAIL_SUBJECT_REQUEST = 'POLICY_DETAIL_SUBJECT_REQUEST';
export const POLICY_DETAIL_SUBJECT_SUCCESS = 'POLICY_DETAIL_SUBJECT_SUCCESS';
export const POLICY_DETAIL_SUBJECT_FAILURE = 'POLICY_DETAIL_SUBJECT_FAILURE';
export type POLICY_DETAIL_SUBJECT_REQUEST = typeof POLICY_DETAIL_SUBJECT_REQUEST;
export type POLICY_DETAIL_SUBJECT_SUCCESS = typeof POLICY_DETAIL_SUBJECT_SUCCESS;
export type POLICY_DETAIL_SUBJECT_FAILURE = typeof POLICY_DETAIL_SUBJECT_FAILURE;

export const POLICY_DETAIL_RISKTYPE_REQUEST = 'POLICY_DETAIL_RISKTYPE_REQUEST';
export const POLICY_DETAIL_RISKTYPE_SUCCESS = 'POLICY_DETAIL_RISKTYPE_SUCCESS';
export const POLICY_DETAIL_RISKTYPE_FAILURE = 'POLICY_DETAIL_RISKTYPE_FAILURE';
export type POLICY_DETAIL_RISKTYPE_REQUEST = typeof POLICY_DETAIL_RISKTYPE_REQUEST;
export type POLICY_DETAIL_RISKTYPE_SUCCESS = typeof POLICY_DETAIL_RISKTYPE_SUCCESS;
export type POLICY_DETAIL_RISKTYPE_FAILURE = typeof POLICY_DETAIL_RISKTYPE_FAILURE;

export const POLICY_DETAIL_EMPLOYEE_LIST_REQUEST = 'POLICY_DETAIL_EMPLOYEE_LIST_REQUEST';
export const POLICY_DETAIL_EMPLOYEE_LIST_SUCCESS = 'POLICY_DETAIL_EMPLOYEE_LIST_SUCCESS';
export const POLICY_DETAIL_EMPLOYEE_LIST_FAILURE = 'POLICY_DETAIL_EMPLOYEE_LIST_FAILURE';
export type POLICY_DETAIL_EMPLOYEE_LIST_REQUEST = typeof POLICY_DETAIL_EMPLOYEE_LIST_REQUEST;
export type POLICY_DETAIL_EMPLOYEE_LIST_SUCCESS = typeof POLICY_DETAIL_EMPLOYEE_LIST_SUCCESS;
export type POLICY_DETAIL_EMPLOYEE_LIST_FAILURE = typeof POLICY_DETAIL_EMPLOYEE_LIST_FAILURE;

export const POLICY_DETAIL_PAY_VISIBLE = 'POLICY_DETAIL_PAY_VISIBLE';
export type POLICY_DETAIL_PAY_VISIBLE = typeof POLICY_DETAIL_PAY_VISIBLE;

export const SET_POLICY_VISIBLE = 'SET_POLICY_VISIBLE';
export type SET_POLICY_VISIBLE = typeof SET_POLICY_VISIBLE;

export const POLICY_IMPORT_REQUEST = 'POLICY_IMPORT_REQUEST';
export const POLICY_IMPORT_SUCCESS = 'POLICY_IMPORT_SUCCESS';
export const POLICY_IMPORT_FAILURE = 'POLICY_IMPORT_FAILURE';
export type POLICY_IMPORT_REQUEST = typeof POLICY_IMPORT_REQUEST;
export type POLICY_IMPORT_SUCCESS = typeof POLICY_IMPORT_SUCCESS;
export type POLICY_IMPORT_FAILURE = typeof POLICY_IMPORT_FAILURE;

export const POLICY_QZIMPORT_REQUEST = 'POLICY_QZIMPORT_REQUEST';
export const POLICY_QZIMPORT_SUCCESS = 'POLICY_QZIMPORT_SUCCESS';
export const POLICY_QZIMPORT_FAILURE = 'POLICY_QZIMPORT_FAILURE';
export type POLICY_QZIMPORT_REQUEST = typeof POLICY_QZIMPORT_REQUEST;
export type POLICY_QZIMPORT_SUCCESS = typeof POLICY_QZIMPORT_SUCCESS;
export type POLICY_QZIMPORT_FAILURE = typeof POLICY_QZIMPORT_FAILURE;

export const COMMISSION_SHOW_KEY = 'COMMISSION_SHOW_KEY';
export type COMMISSION_SHOW_KEY = typeof COMMISSION_SHOW_KEY;

export const COMMISSION_REQUEST = 'COMMISSION_REQUEST';
export const COMMISSION_SUCCESS = 'COMMISSION_SUCCESS';
export const COMMISSION_FAILURE = 'COMMISSION_FAILURE';
export type COMMISSION_REQUEST = typeof COMMISSION_REQUEST;
export type COMMISSION_SUCCESS = typeof COMMISSION_SUCCESS;
export type COMMISSION_FAILURE = typeof COMMISSION_FAILURE;

export const COMMISSION_ADDORMODIFY_REQUEST = 'COMMISSION_ADDORMODIFY_REQUEST';
export const COMMISSION_ADDORMODIFY_SUCCESS = 'COMMISSION_ADDORMODIFY_SUCCESS';
export const COMMISSION_ADDORMODIFY_FAILURE = 'COMMISSION_ADDORMODIFY_FAILURE';
export type COMMISSION_ADDORMODIFY_REQUEST = typeof COMMISSION_ADDORMODIFY_REQUEST;
export type COMMISSION_ADDORMODIFY_SUCCESS = typeof COMMISSION_ADDORMODIFY_SUCCESS;
export type COMMISSION_ADDORMODIFY_FAILURE = typeof COMMISSION_ADDORMODIFY_FAILURE;

export const COMMISSION_DETAIL_REQUEST = 'COMMISSION_DETAIL_REQUEST';
export const COMMISSION_DETAIL_SUCCESS = 'COMMISSION_DETAIL_SUCCESS';
export const COMMISSION_DETAIL_FAILURE = 'COMMISSION_DETAIL_FAILURE';
export type COMMISSION_DETAIL_REQUEST = typeof COMMISSION_DETAIL_REQUEST;
export type COMMISSION_DETAIL_SUCCESS = typeof COMMISSION_DETAIL_SUCCESS;
export type COMMISSION_DETAIL_FAILURE = typeof COMMISSION_DETAIL_FAILURE;

export const COMPANY_SHOW_KEY = 'COMPANY_SHOW_KEY';
export type COMPANY_SHOW_KEY = typeof COMPANY_SHOW_KEY;

export const COMPANY_SET_LEVEL = 'COMPANY_SET_LEVEL';
export type COMPANY_SET_LEVEL = typeof COMPANY_SET_LEVEL;

export const COMPANY_REQUEST = 'COMPANY_REQUEST';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';
export const COMPANY_FAILURE = 'COMPANY_FAILURE';
export type COMPANY_REQUEST = typeof COMPANY_REQUEST;
export type COMPANY_SUCCESS = typeof COMPANY_SUCCESS;
export type COMPANY_FAILURE = typeof COMPANY_FAILURE;

export const COMPANY_ADDORMODIFY_REQUEST = 'COMPANY_ADDORMODIFY_REQUEST';
export const COMPANY_ADDORMODIFY_SUCCESS = 'COMPANY_ADDORMODIFY_SUCCESS';
export const COMPANY_ADDORMODIFY_FAILURE = 'COMPANY_ADDORMODIFY_FAILURE';
export type COMPANY_ADDORMODIFY_REQUEST = typeof COMPANY_ADDORMODIFY_REQUEST;
export type COMPANY_ADDORMODIFY_SUCCESS = typeof COMPANY_ADDORMODIFY_SUCCESS;
export type COMPANY_ADDORMODIFY_FAILURE = typeof COMPANY_ADDORMODIFY_FAILURE;

export const COMPANY_DETAIL_REQUEST = 'COMPANY_DETAIL_REQUEST';
export const COMPANY_DETAIL_SUCCESS = 'COMPANY_DETAIL_SUCCESS';
export const COMPANY_DETAIL_FAILURE = 'COMPANY_DETAIL_FAILURE';
export type COMPANY_DETAIL_REQUEST = typeof COMPANY_DETAIL_REQUEST;
export type COMPANY_DETAIL_SUCCESS = typeof COMPANY_DETAIL_SUCCESS;
export type COMPANY_DETAIL_FAILURE = typeof COMPANY_DETAIL_FAILURE;

export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST';
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_FAILURE = 'COMPANY_DELETE_FAILURE';
export type COMPANY_DELETE_REQUEST = typeof COMPANY_DELETE_REQUEST;
export type COMPANY_DELETE_SUCCESS = typeof COMPANY_DELETE_SUCCESS;
export type COMPANY_DELETE_FAILURE = typeof COMPANY_DELETE_FAILURE;

export const COMPANY_SECOND_REQUEST = 'COMPANY_SECOND_REQUEST';
export const COMPANY_SECOND_SUCCESS = 'COMPANY_SECOND_SUCCESS';
export const COMPANY_SECOND_FAILURE = 'COMPANY_SECOND_FAILURE';
export type COMPANY_SECOND_REQUEST = typeof COMPANY_SECOND_REQUEST;
export type COMPANY_SECOND_SUCCESS = typeof COMPANY_SECOND_SUCCESS;
export type COMPANY_SECOND_FAILURE = typeof COMPANY_SECOND_FAILURE;

export const COMPANY_SECOND_ADDORMODIFY_REQUEST = 'COMPANY_SECOND_ADDORMODIFY_REQUEST';
export const COMPANY_SECOND_ADDORMODIFY_SUCCESS = 'COMPANY_SECOND_ADDORMODIFY_SUCCESS';
export const COMPANY_SECOND_ADDORMODIFY_FAILURE = 'COMPANY_SECOND_ADDORMODIFY_FAILURE';
export type COMPANY_SECOND_ADDORMODIFY_REQUEST = typeof COMPANY_SECOND_ADDORMODIFY_REQUEST;
export type COMPANY_SECOND_ADDORMODIFY_SUCCESS = typeof COMPANY_SECOND_ADDORMODIFY_SUCCESS;
export type COMPANY_SECOND_ADDORMODIFY_FAILURE = typeof COMPANY_SECOND_ADDORMODIFY_FAILURE;

export const COMPANY_SECOND_DETAIL_REQUEST = 'COMPANY_SECOND_DETAIL_REQUEST';
export const COMPANY_SECOND_DETAIL_SUCCESS = 'COMPANY_SECOND_DETAIL_SUCCESS';
export const COMPANY_SECOND_DETAIL_FAILURE = 'COMPANY_SECOND_DETAIL_FAILURE';
export type COMPANY_SECOND_DETAIL_REQUEST = typeof COMPANY_SECOND_DETAIL_REQUEST;
export type COMPANY_SECOND_DETAIL_SUCCESS = typeof COMPANY_SECOND_DETAIL_SUCCESS;
export type COMPANY_SECOND_DETAIL_FAILURE = typeof COMPANY_SECOND_DETAIL_FAILURE;

export const COMPANY_SECOND_DELETE_REQUEST = 'COMPANY_SECOND_DELETE_REQUEST';
export const COMPANY_SECOND_DELETE_SUCCESS = 'COMPANY_SECOND_DELETE_SUCCESS';
export const COMPANY_SECOND_DELETE_FAILURE = 'COMPANY_SECOND_DELETE_FAILURE';
export type COMPANY_SECOND_DELETE_REQUEST = typeof COMPANY_SECOND_DELETE_REQUEST;
export type COMPANY_SECOND_DELETE_SUCCESS = typeof COMPANY_SECOND_DELETE_SUCCESS;
export type COMPANY_SECOND_DELETE_FAILURE = typeof COMPANY_SECOND_DELETE_FAILURE;

export const COMPANY_SET_EXPANDED_ROWKEYS = 'COMPANY_SET_EXPANDED_ROWKEYS';
export type COMPANY_SET_EXPANDED_ROWKEYS = typeof COMPANY_SET_EXPANDED_ROWKEYS;

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';
export type PAYMENT_REQUEST = typeof PAYMENT_REQUEST;
export type PAYMENT_SUCCESS = typeof PAYMENT_SUCCESS;
export type PAYMENT_FAILURE = typeof PAYMENT_FAILURE;

export const REPORT_REQUEST = 'REPORT_REQUEST';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAILURE = 'REPORT_FAILURE';
export type REPORT_REQUEST = typeof REPORT_REQUEST;
export type REPORT_SUCCESS = typeof REPORT_SUCCESS;
export type REPORT_FAILURE = typeof REPORT_FAILURE;

export const REPORT_COMPANY_REQUEST = 'REPORT_COMPANY_REQUEST';
export const REPORT_COMPANY_SUCCESS = 'REPORT_COMPANY_SUCCESS';
export const REPORT_COMPANY_FAILURE = 'REPORT_COMPANY_FAILURE';
export type REPORT_COMPANY_REQUEST = typeof REPORT_COMPANY_REQUEST;
export type REPORT_COMPANY_SUCCESS = typeof REPORT_COMPANY_SUCCESS;
export type REPORT_COMPANY_FAILURE = typeof REPORT_COMPANY_FAILURE;

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export type USER_LOGIN_REQUEST = typeof USER_LOGIN_REQUEST;
export type USER_LOGIN_SUCCESS = typeof USER_LOGIN_SUCCESS;
export type USER_LOGIN_FAILURE = typeof USER_LOGIN_FAILURE;

export const USER_LOGIN_MOCK = 'USER_LOGIN_MOCK';
export type USER_LOGIN_MOCK = typeof USER_LOGIN_MOCK;

export const USER_INFO_MOCK = 'USER_INFO_MOCK';
export type USER_INFO_MOCK = typeof USER_INFO_MOCK;

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';
export type USER_LIST_REQUEST = typeof USER_LIST_REQUEST;
export type USER_LIST_SUCCESS = typeof USER_LIST_SUCCESS;
export type USER_LIST_FAILURE = typeof USER_LIST_FAILURE;

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';
export type USER_INFO_REQUEST = typeof USER_INFO_REQUEST;
export type USER_INFO_SUCCESS = typeof USER_INFO_SUCCESS;
export type USER_INFO_FAILURE = typeof USER_INFO_FAILURE;

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';
export type USER_LOGOUT_REQUEST = typeof USER_LOGOUT_REQUEST;
export type USER_LOGOUT_SUCCESS = typeof USER_LOGOUT_SUCCESS;
export type USER_LOGOUT_FAILURE = typeof USER_LOGOUT_FAILURE;

export const USER_CHANNEL_VISIBLE = 'USER_CHANNEL_VISIBLE';
export type USER_CHANNEL_VISIBLE = typeof USER_CHANNEL_VISIBLE;

export const USER_SYNC_VISIBLE = 'USER_SYNC_VISIBLE';
export type USER_SYNC_VISIBLE = typeof USER_SYNC_VISIBLE;

export const USER_BIND_CHANNEL_MODAL = 'USER_BIND_CHANNEL_MODAL';
export type USER_BIND_CHANNEL_MODAL = typeof USER_BIND_CHANNEL_MODAL;

export const USER_BIND_CHANNEL_REQUEST = 'USER_BIND_CHANNEL_REQUEST';
export const USER_BIND_CHANNEL_SUCCESS = 'USER_BIND_CHANNEL_SUCCESS';
export const USER_BIND_CHANNEL_FAILURE = 'USER_BIND_CHANNEL_FAILURE';
export type USER_BIND_CHANNEL_REQUEST = typeof USER_BIND_CHANNEL_REQUEST;
export type USER_BIND_CHANNEL_SUCCESS = typeof USER_BIND_CHANNEL_SUCCESS;
export type USER_BIND_CHANNEL_FAILURE = typeof USER_BIND_CHANNEL_FAILURE;

export const USER_DETAIL = 'USER_DETAIL';
export type USER_DETAIL = typeof USER_DETAIL;

export const USER_SYNC_REQUEST = 'USER_SYNC_REQUEST';
export const USER_SYNC_SUCCESS = 'USER_SYNC_SUCCESS';
export const USER_SYNC_FAILURE = 'USER_SYNC_FAILURE';
export type USER_SYNC_REQUEST = typeof USER_SYNC_REQUEST;
export type USER_SYNC_SUCCESS = typeof USER_SYNC_SUCCESS;
export type USER_SYNC_FAILURE = typeof USER_SYNC_FAILURE;

export const DATAX_LIST_REQUEST = 'DATAX_LIST_REQUEST';
export const DATAX_LIST_SUCCESS = 'DATAX_LIST_SUCCESS';
export const DATAX_LIST_FAILURE = 'DATAX_LIST_FAILURE';
export type DATAX_LIST_REQUEST = typeof DATAX_LIST_REQUEST;
export type DATAX_LIST_SUCCESS = typeof DATAX_LIST_SUCCESS;
export type DATAX_LIST_FAILURE = typeof DATAX_LIST_FAILURE;

export const DATAX_UPLOAD_REQUEST = 'DATAX_UPLOAD_REQUEST';
export const DATAX_UPLOAD_SUCCESS = 'DATAX_UPLOAD_SUCCESS';
export const DATAX_UPLOAD_FAILURE = 'DATAX_UPLOAD_FAILURE';
export type DATAX_UPLOAD_REQUEST = typeof DATAX_UPLOAD_REQUEST;
export type DATAX_UPLOAD_SUCCESS = typeof DATAX_UPLOAD_SUCCESS;
export type DATAX_UPLOAD_FAILURE = typeof DATAX_UPLOAD_FAILURE;

export const DATAX_LIST_VISIBLE = 'DATAX_LIST_VISIBLE';
export type DATAX_LIST_VISIBLE = typeof DATAX_LIST_VISIBLE;

export const DATAX_SELECTED_LIST = 'DATAX_SELECTED_LIST';
export type DATAX_SELECTED_LIST = typeof DATAX_SELECTED_LIST;

export const DATAX_SELECTED_SET = 'DATAX_SELECTED_SET';
export type DATAX_SELECTED_SET = typeof DATAX_SELECTED_SET;

export const COMPANY_GLOBAL_LIST_REQUEST = 'COMPANY_GLOBAL_LIST_REQUEST';
export const COMPANY_GLOBAL_LIST_SUCCESS = 'COMPANY_GLOBAL_LIST_SUCCESS';
export const COMPANY_GLOBAL_LIST_FAILURE = 'COMPANY_GLOBAL_LIST_FAILURE';
export type COMPANY_GLOBAL_LIST_REQUEST = typeof COMPANY_GLOBAL_LIST_REQUEST;
export type COMPANY_GLOBAL_LIST_SUCCESS = typeof COMPANY_GLOBAL_LIST_SUCCESS;
export type COMPANY_GLOBAL_LIST_FAILURE = typeof COMPANY_GLOBAL_LIST_FAILURE;

export const COMPANY_LIST_VISIBLE = 'COMPANY_LIST_VISIBLE';
export type COMPANY_LIST_VISIBLE = typeof COMPANY_LIST_VISIBLE;

export const COMPANY_SELECTED_SET = 'COMPANY_SELECTED_SET';
export type COMPANY_SELECTED_SET = typeof COMPANY_SELECTED_SET;

export const NCVOUCHER_LIST_REQUEST = 'NCVOUCHER_LIST_REQUEST';
export const NCVOUCHER_LIST_SUCCESS = 'NCVOUCHER_LIST_SUCCESS';
export const NCVOUCHER_LIST_FAILURE = 'NCVOUCHER_LIST_FAILURE';
export type NCVOUCHER_LIST_REQUEST = typeof NCVOUCHER_LIST_REQUEST;
export type NCVOUCHER_LIST_SUCCESS = typeof NCVOUCHER_LIST_SUCCESS;
export type NCVOUCHER_LIST_FAILURE = typeof NCVOUCHER_LIST_FAILURE;

export const NCVOUCHER_PREPARE_AND_UPLOAD_REQUEST = 'NCVOUCHER_PREPARE_AND_UPLOAD_REQUEST';
export const NCVOUCHER_PREPARE_AND_UPLOAD_SUCCESS = 'NCVOUCHER_PREPARE_AND_UPLOAD_SUCCESS';
export const NCVOUCHER_PREPARE_AND_UPLOAD_FAILURE = 'NCVOUCHER_PREPARE_AND_UPLOAD_FAILURE';
export type NCVOUCHER_PREPARE_AND_UPLOAD_REQUEST = typeof NCVOUCHER_PREPARE_AND_UPLOAD_REQUEST;
export type NCVOUCHER_PREPARE_AND_UPLOAD_SUCCESS = typeof NCVOUCHER_PREPARE_AND_UPLOAD_SUCCESS;
export type NCVOUCHER_PREPARE_AND_UPLOAD_FAILURE = typeof NCVOUCHER_PREPARE_AND_UPLOAD_FAILURE;

export const NCVOUCHER_UPLOAD_VISIBLE = 'NCVOUCHER_UPLOAD_VISIBLE';
export type NCVOUCHER_UPLOAD_VISIBLE = typeof NCVOUCHER_UPLOAD_VISIBLE;

export const INSURE_SET_STEP = 'INSURE_SET_STEP';
export type INSURE_SET_STEP = typeof INSURE_SET_STEP;

export const INSURE_SET_POLICY_VISIBLE = 'INSURE_SET_POLICY_VISIBLE';
export type INSURE_SET_POLICY_VISIBLE = typeof INSURE_SET_POLICY_VISIBLE;

export const INSURE_SET_PRODUCT = 'INSURE_SET_PRODUCT';
export type INSURE_SET_PRODUCT = typeof INSURE_SET_PRODUCT;

export const INSURE_SET_DECLARE = 'INSURE_SET_DECLARE';
export type INSURE_SET_DECLARE = typeof INSURE_SET_DECLARE;

export const INSURE_INIT = 'INSURE_INIT';
export type INSURE_INIT = typeof INSURE_INIT;

export const INSURE_DECLARE_IMPORT_REQUEST = 'INSURE_DECLARE_IMPORT_REQUEST';
export const INSURE_DECLARE_IMPORT_SUCCESS = 'INSURE_DECLARE_IMPORT_SUCCESS';
export const INSURE_DECLARE_IMPORT_FAILURE = 'INSURE_DECLARE_IMPORT_FAILURE';
export type INSURE_DECLARE_IMPORT_REQUEST = typeof INSURE_DECLARE_IMPORT_REQUEST;

export const INSURE_DECLARE_IMPORT_POLICY_LIST = 'INSURE_DECLARE_IMPORT_POLICY_LIST';
export type INSURE_DECLARE_IMPORT_POLICY_LIST = typeof INSURE_DECLARE_IMPORT_POLICY_LIST;

export const INSURE_DECLARE_IMPORT_POLICY_LIST_SINGLE = 'INSURE_DECLARE_IMPORT_POLICY_LIST_SINGLE';
export type INSURE_DECLARE_IMPORT_POLICY_LIST_SINGLE = typeof INSURE_DECLARE_IMPORT_POLICY_LIST_SINGLE;

export const INSURE_DECLARE_IMPORT_POLICY_LIST_GROUP = 'INSURE_DECLARE_IMPORT_POLICY_LIST_GROUP';
export type INSURE_DECLARE_IMPORT_POLICY_LIST_GROUP = typeof INSURE_DECLARE_IMPORT_POLICY_LIST_GROUP;

export const INSURE_IMPORT_INFO_REQUEST = 'INSURE_IMPORT_INFO_REQUEST';
export const INSURE_IMPORT_INFO_SUCCESS = 'INSURE_IMPORT_INFO_SUCCESS';
export const INSURE_IMPORT_INFO_FAILURE = 'INSURE_IMPORT_INFO_FAILURE';
export type INSURE_IMPORT_INFO_REQUEST = typeof INSURE_IMPORT_INFO_REQUEST;
export type INSURE_IMPORT_INFO_SUCCESS = typeof INSURE_IMPORT_INFO_SUCCESS;
export type INSURE_IMPORT_INFO_FAILURE = typeof INSURE_IMPORT_INFO_FAILURE;

export const INSURE_IMPORT_POLICY_REQUEST = 'INSURE_IMPORT_POLICY_REQUEST';
export const INSURE_IMPORT_POLICY_SUCCESS = 'INSURE_IMPORT_POLICY_SUCCESS';
export const INSURE_IMPORT_POLICY_FAILURE = 'INSURE_IMPORT_POLICY_FAILURE';
export type INSURE_IMPORT_POLICY_REQUEST = typeof INSURE_IMPORT_POLICY_REQUEST;
export type INSURE_IMPORT_POLICY_SUCCESS = typeof INSURE_IMPORT_POLICY_SUCCESS;
export type INSURE_IMPORT_POLICY_FAILURE = typeof INSURE_IMPORT_POLICY_FAILURE;

export const INSURE_POLICY_REQUEST = 'INSURE_POLICY_REQUEST';
export const INSURE_POLICY_SUCCESS = 'INSURE_POLICY_SUCCESS';
export const INSURE_POLICY_FAILURE = 'INSURE_POLICY_FAILURE';
export type INSURE_POLICY_REQUEST = typeof INSURE_POLICY_REQUEST;
export type INSURE_POLICY_SUCCESS = typeof INSURE_POLICY_SUCCESS;
export type INSURE_POLICY_FAILURE = typeof INSURE_POLICY_FAILURE;

export const INSURE_POLICY_LIST_REQUEST = 'INSURE_POLICY_LIST_REQUEST';
export const INSURE_POLICY_LIST_SUCCESS = 'INSURE_POLICY_LIST_SUCCESS';
export const INSURE_POLICY_LIST_FAILURE = 'INSURE_POLICY_LIST_FAILURE';
export type INSURE_POLICY_LIST_REQUEST = typeof INSURE_POLICY_LIST_REQUEST;
export type INSURE_POLICY_LIST_SUCCESS = typeof INSURE_POLICY_LIST_SUCCESS;
export type INSURE_POLICY_LIST_FAILURE = typeof INSURE_POLICY_LIST_FAILURE;

export const INSURE_POLICY_LIST_SINGLE_REQUEST = 'INSURE_POLICY_LIST_SINGLE_REQUEST';
export const INSURE_POLICY_LIST_SINGLE_SUCCESS = 'INSURE_POLICY_LIST_SINGLE_SUCCESS';
export const INSURE_POLICY_LIST_SINGLE_FAILURE = 'INSURE_POLICY_LIST_SINGLE_FAILURE';
export type INSURE_POLICY_LIST_SINGLE_REQUEST = typeof INSURE_POLICY_LIST_SINGLE_REQUEST;
export type INSURE_POLICY_LIST_SINGLE_SUCCESS = typeof INSURE_POLICY_LIST_SINGLE_SUCCESS;
export type INSURE_POLICY_LIST_SINGLE_FAILURE = typeof INSURE_POLICY_LIST_SINGLE_FAILURE;

export const INSURE_POLICY_LIST_GROUP_REQUEST = 'INSURE_POLICY_LIST_GROUP_REQUEST';
export const INSURE_POLICY_LIST_GROUP_SUCCESS = 'INSURE_POLICY_LIST_GROUP_SUCCESS';
export const INSURE_POLICY_LIST_GROUP_FAILURE = 'INSURE_POLICY_LIST_GROUP_FAILURE';
export type INSURE_POLICY_LIST_GROUP_REQUEST = typeof INSURE_POLICY_LIST_GROUP_REQUEST;
export type INSURE_POLICY_LIST_GROUP_SUCCESS = typeof INSURE_POLICY_LIST_GROUP_SUCCESS;
export type INSURE_POLICY_LIST_GROUP_FAILURE = typeof INSURE_POLICY_LIST_GROUP_FAILURE;

export const INSURE_SET_POLICY_LIST = 'INSURE_SET_POLICY_LIST';
export type INSURE_SET_POLICY_LIST = typeof INSURE_SET_POLICY_LIST;

export const INSURE_CONFIRM_REQUEST = 'INSURE_CONFIRM_REQUEST';
export const INSURE_CONFIRM_SUCCESS = 'INSURE_CONFIRM_SUCCESS';
export const INSURE_CONFIRM_FAILURE = 'INSURE_CONFIRM_FAILURE';
export type INSURE_CONFIRM_REQUEST = typeof INSURE_CONFIRM_REQUEST;
export type INSURE_CONFIRM_SUCCESS = typeof INSURE_CONFIRM_SUCCESS;
export type INSURE_CONFIRM_FAILURE = typeof INSURE_CONFIRM_FAILURE;

export const INSURE_STEP_2_INIT = 'INSURE_STEP_2_INIT';
export type INSURE_STEP_2_INIT = typeof INSURE_STEP_2_INIT;

export const INSURE_STEP_3_INIT = 'INSURE_STEP_3_INIT';
export type INSURE_STEP_3_INIT = typeof INSURE_STEP_3_INIT;

export const POLICY_PAY_REQUEST = 'POLICY_PAY_REQUEST';
export const POLICY_PAY_SUCCESS = 'POLICY_PAY_SUCCESS';
export const POLICY_PAY_FAILURE = 'POLICY_PAY_FAILURE';
export type POLICY_PAY_REQUEST = typeof POLICY_PAY_REQUEST;
export type POLICY_PAY_SUCCESS = typeof POLICY_PAY_SUCCESS;
export type POLICY_PAY_FAILURE = typeof POLICY_PAY_FAILURE;

export const POLICY_BATCH_PAY_REQUEST = 'POLICY_BATCH_PAY_REQUEST';
export const POLICY_BATCH_PAY_SUCCESS = 'POLICY_BATCH_PAY_SUCCESS';
export const POLICY_BATCH_PAY_FAILURE = 'POLICY_BATCH_PAY_FAILURE';
export type POLICY_BATCH_PAY_REQUEST = typeof POLICY_BATCH_PAY_REQUEST;
export type POLICY_BATCH_PAY_SUCCESS = typeof POLICY_BATCH_PAY_SUCCESS;
export type POLICY_BATCH_PAY_FAILURE = typeof POLICY_BATCH_PAY_FAILURE;

export const BATCH_POLICY_LIST_REQUEST = 'BATCH_POLICY_LIST_REQUEST';
export const BATCH_POLICY_LIST_SUCCESS = 'BATCH_POLICY_LIST_SUCCESS';
export const BATCH_POLICY_LIST_FAILURE = 'BATCH_POLICY_LIST_FAILURE';
export type BATCH_POLICY_LIST_REQUEST = typeof BATCH_POLICY_LIST_REQUEST;
export type BATCH_POLICY_LIST_SUCCESS = typeof BATCH_POLICY_LIST_SUCCESS;
export type BATCH_POLICY_LIST_FAILURE = typeof BATCH_POLICY_LIST_FAILURE;

export const BATCH_POLICY_SUMMARY_REQUEST = 'BATCH_POLICY_SUMMARY_REQUEST';
export const BATCH_POLICY_SUMMARY_SUCCESS = 'BATCH_POLICY_SUMMARY_SUCCESS';
export const BATCH_POLICY_SUMMARY_FAILURE = 'BATCH_POLICY_SUMMARY_FAILURE';
export type BATCH_POLICY_SUMMARY_REQUEST = typeof BATCH_POLICY_SUMMARY_REQUEST;
export type BATCH_POLICY_SUMMARY_SUCCESS = typeof BATCH_POLICY_SUMMARY_SUCCESS;
export type BATCH_POLICY_SUMMARY_FAILURE = typeof BATCH_POLICY_SUMMARY_FAILURE;

export const BATCH_POLICY_UNDO_SUMMARY_REQUEST = 'BATCH_POLICY_UNDO_SUMMARY_REQUEST';
export const BATCH_POLICY_UNDO_SUMMARY_SUCCESS = 'BATCH_POLICY_UNDO_SUMMARY_SUCCESS';
export const BATCH_POLICY_UNDO_SUMMARY_FAILURE = 'BATCH_POLICY_UNDO_SUMMARY_FAILURE';
export type BATCH_POLICY_UNDO_SUMMARY_REQUEST = typeof BATCH_POLICY_UNDO_SUMMARY_REQUEST;
export type BATCH_POLICY_UNDO_SUMMARY_SUCCESS = typeof BATCH_POLICY_UNDO_SUMMARY_SUCCESS;
export type BATCH_POLICY_UNDO_SUMMARY_FAILURE = typeof BATCH_POLICY_UNDO_SUMMARY_FAILURE;

export const BATCH_POLICY_SEARCH_CLEAR = 'BATCH_POLICY_SEARCH_CLEAR';
export type BATCH_POLICY_SEARCH_CLEAR = typeof BATCH_POLICY_SEARCH_CLEAR;

export const BATCH_POLICY_SELECTED_KEYS = 'BATCH_POLICY_SELECTED_KEYS';
export type BATCH_POLICY_SELECTED_KEYS = typeof BATCH_POLICY_SELECTED_KEYS;

export const BATCH_POLICY_DETAIL_REQUEST = 'BATCH_POLICY_DETAIL_REQUEST';
export const BATCH_POLICY_DETAIL_SUCCESS = 'BATCH_POLICY_DETAIL_SUCCESS';
export const BATCH_POLICY_DETAIL_FAILURE = 'BATCH_POLICY_DETAIL_FAILURE';
export type BATCH_POLICY_DETAIL_REQUEST = typeof BATCH_POLICY_DETAIL_REQUEST;
export type BATCH_POLICY_DETAIL_SUCCESS = typeof BATCH_POLICY_DETAIL_SUCCESS;
export type BATCH_POLICY_DETAIL_FAILURE = typeof BATCH_POLICY_DETAIL_FAILURE;

export const POLICY_MARKET_LIST_REQUEST = 'POLICY_MARKET_LIST_REQUEST';
export const POLICY_MARKET_LIST_SUCCESS = 'POLICY_MARKET_LIST_SUCCESS';
export const POLICY_MARKET_LIST_FAILURE = 'POLICY_MARKET_LIST_FAILURE';
export type POLICY_MARKET_LIST_REQUEST = typeof POLICY_MARKET_LIST_REQUEST;
export type POLICY_MARKET_LIST_SUCCESS = typeof POLICY_MARKET_LIST_SUCCESS;
export type POLICY_MARKET_LIST_FAILURE = typeof POLICY_MARKET_LIST_FAILURE;

export const POLICY_MARKET_IMPORT_REQUEST = 'POLICY_MARKET_IMPORT_REQUEST';
export const POLICY_MARKET_IMPORT_SUCCESS = 'POLICY_MARKET_IMPORT_SUCCESS';
export const POLICY_MARKET_IMPORT_FAILURE = 'POLICY_MARKET_IMPORT_FAILURE';
export type POLICY_MARKET_IMPORT_REQUEST = typeof POLICY_MARKET_IMPORT_REQUEST;
export type POLICY_MARKET_IMPORT_SUCCESS = typeof POLICY_MARKET_IMPORT_SUCCESS;
export type POLICY_MARKET_IMPORT_FAILURE = typeof POLICY_MARKET_IMPORT_FAILURE;

export const POLICY_MARKET_SHOW_KEY = 'POLICY_MARKET_SHOW_KEY';
export type POLICY_MARKET_SHOW_KEY = typeof POLICY_MARKET_SHOW_KEY;

export const POLICY_MARKET_PRODUCT_LIST_REQUEST = 'POLICY_MARKET_PRODUCT_LIST_REQUEST';
export const POLICY_MARKET_PRODUCT_LIST_SUCCESS = 'POLICY_MARKET_PRODUCT_LIST_SUCCESS';
export const POLICY_MARKET_PRODUCT_LIST_FAILURE = 'POLICY_MARKET_PRODUCT_LIST_FAILURE';
export type POLICY_MARKET_PRODUCT_LIST_REQUEST = typeof POLICY_MARKET_PRODUCT_LIST_REQUEST;
export type POLICY_MARKET_PRODUCT_LIST_SUCCESS = typeof POLICY_MARKET_PRODUCT_LIST_SUCCESS;
export type POLICY_MARKET_PRODUCT_LIST_FAILURE = typeof POLICY_MARKET_PRODUCT_LIST_FAILURE;

export const INTENTION_LIST_REQUEST = 'INTENTION_LIST_REQUEST';
export const INTENTION_LIST_SUCCESS = 'INTENTION_LIST_SUCCESS';
export const INTENTION_LIST_FAILURE = 'INTENTION_LIST_FAILURE';
export type INTENTION_LIST_REQUEST = typeof INTENTION_LIST_REQUEST;
export type INTENTION_LIST_SUCCESS = typeof INTENTION_LIST_SUCCESS;
export type INTENTION_LIST_FAILURE = typeof INTENTION_LIST_FAILURE;
