[
  {
    "code": "insurance_company",
    "id": 54856,
    "description": "tbb-broker-web",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "保险公司管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/company",
    "resourceBos": [
      {
        "code": "insurance_company_list",
        "id": 54857,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保险公司列表",
        "parentId": 54856,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/queryList",
        "resourceBos": []
      },
      {
        "code": "insurance_company_add1",
        "id": 54858,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "添加一级保险公司",
        "parentId": 54856,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/save",
        "resourceBos": []
      },
      {
        "code": "insurance_company_add2",
        "id": 54859,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "添加二级保险公司",
        "parentId": 54856,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/save",
        "resourceBos": []
      },
      {
        "code": "insurance_company_modify",
        "id": 54860,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改保险公司",
        "parentId": 54856,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/save",
        "resourceBos": []
      },
      {
        "code": "insurance_company_detail",
        "id": 54861,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查看保险公司详情",
        "parentId": 54856,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/queryById",
        "resourceBos": []
      },
      {
        "code": "insurance_company_delete",
        "id": 54862,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "删除保险公司",
        "parentId": 54856,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/delete",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_product",
    "id": 54863,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "产品管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/product",
    "resourceBos": [
      {
        "code": "insurance_product_list",
        "id": 54864,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "产品列表",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/list",
        "resourceBos": []
      },
      {
        "code": "insurance_product_add",
        "id": 54865,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "添加产品",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/add",
        "resourceBos": [
          {
            "code": "addHtml",
            "id": 54866,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "修改H5",
            "parentId": 54865,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/productManagement/addHtml",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_product_modify",
        "id": 54867,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改产品",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/update",
        "resourceBos": []
      },
      {
        "code": "insurance_product_detail",
        "id": 54868,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查看产品详情",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/queryById",
        "resourceBos": [
          {
            "code": "insurance_product_h5_iframe",
            "id": 54869,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "查看产品h5_iframe",
            "parentId": 54868,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/productManagement/queryHtmlPageById",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_product_modify_h5",
        "id": 54870,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改产品H5",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/updateHtml",
        "resourceBos": []
      },
      {
        "code": "insurance_product_h5",
        "id": 54871,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询产品h5",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/queryHtmlById",
        "resourceBos": []
      },
      {
        "code": "insurance_product_update_status",
        "id": 54872,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "更新产品状态",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/productManagement/updateStatus",
        "resourceBos": []
      },
      {
        "code": "Insure_Company_queryLike",
        "id": 54873,
        "description": "添加产品，查询保险公司列表",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询保险公司列表",
        "parentId": 54863,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insureCompany/queryLike",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_channel",
    "id": 54874,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "渠道管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/channel",
    "resourceBos": [
      {
        "code": "insurance_channel_list",
        "id": 54875,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "渠道列表",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/getByKeywords",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_add",
        "id": 54876,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "新增渠道",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/insert",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_modify",
        "id": 54877,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改渠道",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/update",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_detail",
        "id": 54878,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查看渠道详情",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/getDetail",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_update_status",
        "id": 54879,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "更新渠道状态",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/updateChannelStatus",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_update_sec",
        "id": 54880,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "更新渠道密钥",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/updateChannelSec",
        "resourceBos": []
      },
      {
        "code": "insurance_sub_channel_add",
        "id": 54881,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "新增子渠道",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/insert",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_getChannelTree",
        "id": 54882,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "渠道树",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/get-channel-tree",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_childrenChannelTree",
        "id": 54883,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "子渠道树",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/get-children-channel-tree",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_levels",
        "id": 54884,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "渠道等级",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/get-channel-levels",
        "resourceBos": []
      },
      {
        "code": "insurance_channel_status_before",
        "id": 54885,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "更新渠道状态前置接口",
        "parentId": 54874,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/baseChannelInfo/before-updateChannelStatus",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_commission",
    "id": 54886,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "渠道费用配置",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/commission",
    "resourceBos": [
      {
        "code": "insurance_commission_list",
        "id": 54887,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "渠道费用列表",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/list",
        "resourceBos": []
      },
      {
        "code": "insurance_commission_modify",
        "id": 54888,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改渠道费用",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/update",
        "resourceBos": []
      },
      {
        "code": "insurance_commission_add",
        "id": 54889,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "添加渠道费用",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/insert",
        "resourceBos": []
      },
      {
        "code": "insurance_commission_detail",
        "id": 54890,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询渠道费用详情",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/getDetail",
        "resourceBos": []
      },
      {
        "code": "insurance_commission_get_products",
        "id": 54891,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询渠道方产品列表",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/get-products",
        "resourceBos": []
      },
      {
        "code": "insurance_commission_get_parent_products",
        "id": 54892,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询渠道方产品列表2",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/get-parent-products",
        "resourceBos": []
      },
      {
        "code": "insurance_commission_get_parent_detail",
        "id": 54893,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询父渠道费用比例和时间",
        "parentId": 54886,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/channelCommissionInfo/get-parent-detail",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_policy",
    "id": 54894,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "保单管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/policy",
    "resourceBos": [
      {
        "code": "insurance_policy_detail",
        "id": 54895,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 1,
        "name": "保单详情",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insurance/policy/detail",
        "resourceBos": [
          {
            "code": "insurance_policy_detail_base",
            "id": 54896,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单基本详情",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/basePolicy/queryById",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_subject",
            "id": 54897,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单标的详情",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getSubjectDetail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_riskType",
            "id": 54898,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 1,
            "name": "保单险别信息",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policyType/queryByBusinessNo",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_appli",
            "id": 54899,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单投保人信息",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getApplyDetail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_recognizee",
            "id": 54900,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单投保人信息",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getRecognizeeDetail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_favoree",
            "id": 54901,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单受益人信息",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getFavoreeDetail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_pay",
            "id": 54902,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单缴费信息",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getPayDetail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_fee",
            "id": 54903,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单费用信息",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getFeeDetial",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_clause",
            "id": 54904,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单特别约定",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getClauseInfo",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_payment_detail",
            "id": 54905,
            "description": "保单详情---缴费信息---缴费计划。",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "查询缴费计划",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/policy/getPaymentDetail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_detail_refund",
            "id": 54985,
            "description": "保单详情---缴费信息---退保退费",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "退保退费",
            "parentId": 54895,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/refund",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_policy_list",
        "id": 54906,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单列表",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/policy/list",
        "resourceBos": []
      },
      {
        "code": "insurance_policy_import",
        "id": 54907,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单导入",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net",
        "resourceBos": [
          {
            "code": "insurance_policy_import_account_excel",
            "id": 54908,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单excel导入(结算)",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/file/importExcelSettleAccounts",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_import_excel",
            "id": 54909,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单excel导入(不结算)",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/file/importExcel",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_import_account_datax",
            "id": 54910,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单datax导入(结算)",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/file/importDataxSettleAccounts",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_import_datax",
            "id": 54911,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "保单datax导入(不结算)",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/file/importDatax",
            "resourceBos": []
          },
          {
            "code": "productList_by_company",
            "id": 54912,
            "description": "保单导入，根据保险机构查产品",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "根据保险机构查产品",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/productManagement/productListByCompany",
            "resourceBos": []
          },
          {
            "code": "query_by_produceNo",
            "id": 54913,
            "description": "根据产品查询渠道",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "根据产品查询渠道",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/baseChannelInfo/queryByProduceNo",
            "resourceBos": []
          },
          {
            "code": "datax_list",
            "id": 54914,
            "description": "datax文件列表",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "datax文件列表",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/datax/list",
            "resourceBos": []
          },
          {
            "code": "insurance_import_policy_from_excel",
            "id": 54915,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "Excel保单导入(new)",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/file/importPolicyFromExcel",
            "resourceBos": []
          },
          {
            "code": "insurance_import_excel_from_datax",
            "id": 54916,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "datax导入Excel(new)",
            "parentId": 54907,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "http://oper.tongbb.net/file/importPolicyFromDatax",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_policy_export",
        "id": 54917,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单导出",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/file/exportDataToExcel",
        "resourceBos": []
      },
      {
        "code": "insurance_policy_template",
        "id": 54918,
        "description": "保单模板",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单导入模板",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/excel/download",
        "resourceBos": []
      },
      {
        "code": "insurance_policy_qzimport",
        "id": 54919,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单导入--轻住",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net//file/importPolicyFromQingzhu",
        "resourceBos": []
      },
      {
        "code": "proposal-recall",
        "id": 54920,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单回溯",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/policy/get-recall",
        "resourceBos": []
      },
      {
        "code": "proposal-recall-page",
        "id": 54921,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单回溯页面",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/recall",
        "resourceBos": []
      },
      {
        "code": "file_import_Refund",
        "id": 54986,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "退保模版导入",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/file/importRefund",
        "resourceBos": []
      },
      {
        "code": "policy_getSurrenderInfo",
        "id": 54987,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "退保信息查询",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/policy/getSurrenderInfo",
        "resourceBos": []
      },
      {
        "code": "insurance_policy_hyx",
        "id": 55001,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "货运险",
        "parentId": 54894,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/policy/hyx",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_repayment",
    "id": 54922,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "收付列表",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/repayment",
    "resourceBos": [
      {
        "code": "insurance_repayment_list",
        "id": 54923,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "收付列表",
        "parentId": 54922,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/policyCharge/queryPayList",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_report",
    "id": 54924,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "收付日列表",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/report",
    "resourceBos": [
      {
        "code": "insurance_report_list",
        "id": 54925,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "收付日列表",
        "parentId": 54924,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/policyCharge/query",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_userChannel",
    "id": 54926,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "用户渠道管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 0,
    "url": "http://oper.tongbb.net/insurance/userChannel",
    "resourceBos": [
      {
        "code": "insurance_userChannel_list",
        "id": 54927,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "用户列表",
        "parentId": 54926,
        "position": null,
        "visible": false,
        "status": 0,
        "url": "http://oper.tongbb.net/user/list",
        "resourceBos": []
      },
      {
        "code": "insurance_userChannel_bind",
        "id": 54928,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "用户绑定渠道",
        "parentId": 54926,
        "position": null,
        "visible": false,
        "status": 0,
        "url": "http://oper.tongbb.net/user/updateUser",
        "resourceBos": []
      },
      {
        "code": "insurance_userChannel_modify",
        "id": 54929,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "更新用户渠道",
        "parentId": 54926,
        "position": null,
        "visible": false,
        "status": 0,
        "url": "http://oper.tongbb.net/user/updateUser",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_ncVoucher",
    "id": 54930,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "NC凭证历史记录",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/ncVoucher",
    "resourceBos": [
      {
        "code": "insurance_ncVoucher_list",
        "id": 54931,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "NC凭证历史记录列表",
        "parentId": 54930,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/ncVoucher/queryHistory",
        "resourceBos": []
      },
      {
        "code": "insurance_ncVoucher_prepare_and_upload",
        "id": 54932,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "NC凭证生成并上传",
        "parentId": 54930,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/ncVoucher/prepareAndUploadVoucher",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_market",
    "id": 54933,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "保单营销管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/market",
    "resourceBos": [
      {
        "code": "insurance_policy_market_list",
        "id": 54934,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单列表",
        "parentId": 54933,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/mkt/getPolicyInfo",
        "resourceBos": []
      },
      {
        "code": "insurance_policy_market_import",
        "id": 54935,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "保单导入",
        "parentId": 54933,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/mkt/policy.import/v1",
        "resourceBos": []
      },
      {
        "code": "insurance_policy_market_product_list",
        "id": 54936,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "产品列表",
        "parentId": 54933,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/mkt/getProductNameList",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_intention",
    "id": 54937,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "保单意向查询",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/intention",
    "resourceBos": [
      {
        "code": "insurance_intention_list",
        "id": 54938,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查询列表",
        "parentId": 54937,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net",
        "resourceBos": []
      },
      {
        "code": "insurance_intention_export_policy",
        "id": 54939,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "导出投保清单",
        "parentId": 54937,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http:",
        "resourceBos": []
      },
      {
        "code": "insurance_intention_export_employee",
        "id": 54940,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "导出雇员清单",
        "parentId": 54937,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http:",
        "resourceBos": []
      },
      {
        "code": "insurance_intention_export_image",
        "id": 54941,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "导出影像资料",
        "parentId": 54937,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http:",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_activity",
    "id": 54942,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "活动页面管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/activity",
    "resourceBos": [
      {
        "code": "insurance_activity_list",
        "id": 54943,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "活动页面列表",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/list",
        "resourceBos": []
      },
      {
        "code": "insurance_activity_save",
        "id": 54944,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "新增活动页面",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/save",
        "resourceBos": []
      },
      {
        "code": "insurance_activity_update",
        "id": 54945,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改活动管理",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/update",
        "resourceBos": []
      },
      {
        "code": "insurance_activity_delete",
        "id": 54946,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "删除活动管理",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/delete",
        "resourceBos": []
      },
      {
        "code": "insurance_activity_queryByID",
        "id": 54947,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "活动管理详情",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/queryByID",
        "resourceBos": []
      },
      {
        "code": "insurance_activity_update_channels",
        "id": 54948,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "更新活动渠道状态",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/updateChannels",
        "resourceBos": []
      },
      {
        "code": "insurance_activity_queryChannelByactivity",
        "id": 54949,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "根据活动查渠道",
        "parentId": 54942,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/activity/getChannelsByActivityNo",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_link",
    "id": 54950,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "链接管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/link",
    "resourceBos": [
      {
        "code": "insurance_link_generate",
        "id": 54951,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "新增链接管理",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link/generate",
        "resourceBos": []
      },
      {
        "code": "insurance_link_query",
        "id": 54952,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "链接管理列表",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link/query",
        "resourceBos": []
      },
      {
        "code": "insurance_link_delete",
        "id": 54953,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "删除链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link/delete",
        "resourceBos": []
      },
      {
        "code": "insurance_link_update",
        "id": 54954,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link/update",
        "resourceBos": []
      },
      {
        "code": "insurance_link_exportExcel",
        "id": 54955,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "导出链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link/exportExcel",
        "resourceBos": []
      },
      {
        "code": "insurance_link_updateBatch",
        "id": 54956,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "批量修改链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link/updateBatch",
        "resourceBos": []
      },
      {
        "code": "insurance_link_deleteBatch",
        "id": 54957,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "批量删除链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/link_deleteBatch",
        "resourceBos": []
      },
      {
        "code": "insurance_link_combination",
        "id": 54973,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "组合关系",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insurance/link/combination",
        "resourceBos": [
          {
            "code": "link_relation_query",
            "id": 54980,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "组合关系列表",
            "parentId": 54973,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/link/relation/query",
            "resourceBos": []
          },
          {
            "code": "link_relation_status_change",
            "id": 54981,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "组合关系状态修改",
            "parentId": 54973,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/link/relation/status/change",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_link_launch",
        "id": 54974,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "投放链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insurance/link/launch",
        "resourceBos": [
          {
            "code": "link_detail",
            "id": 54982,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "链接详情",
            "parentId": 54974,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/link/detail",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_link_notlaunch",
        "id": 54975,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "非投放链接",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/insurance/link/notlaunch",
        "resourceBos": [
          {
            "code": "link_all_relation_status_change",
            "id": 54984,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "链接关系批量修改",
            "parentId": 54975,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/link/all/relation/status/change",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_link_combinationconfig",
        "id": 54978,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "组合链接配置",
        "parentId": 54950,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/link/combinationconfig",
        "resourceBos": [
          {
            "code": "link_combine",
            "id": 54979,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "组合链接",
            "parentId": 54978,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/link/combine",
            "resourceBos": []
          }
        ]
      }
    ]
  },
  {
    "code": "insurance_statistics",
    "id": 54958,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "统计管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/statistics",
    "resourceBos": [
      {
        "code": "insurance_statistic_list",
        "id": 54959,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "统计列表",
        "parentId": 54958,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/statistic/list",
        "resourceBos": []
      },
      {
        "code": "insurance_statistics_exportExcel",
        "id": 54960,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "统计导出",
        "parentId": 54958,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/statistic/exportExcel",
        "resourceBos": []
      },
      {
        "code": "insurance_statistics_getTrackDetail",
        "id": 54961,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "统计跟踪",
        "parentId": 54958,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/statistic/getTrackDetail",
        "resourceBos": []
      },
      {
        "code": "insurance_statistics_exportExcelWithTrack",
        "id": 54962,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "导出统计跟踪",
        "parentId": 54958,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/statistic/exportExcelWithTrack",
        "resourceBos": []
      },
      {
        "code": "report_policy_detail_summary",
        "id": 54976,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "百万医疗保单导出",
        "parentId": 54958,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/report/policy/detail/summary",
        "resourceBos": []
      },
      {
        "code": "report_gift_policy_detail_summary",
        "id": 54977,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "赠险保单导出",
        "parentId": 54958,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/report/gift/policy/detail/summary",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_partner",
    "id": 54963,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "合作方管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "http://oper.tongbb.net/insurance/partner",
    "resourceBos": [
      {
        "code": "insurance_partner_list",
        "id": 54964,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "合作方列表",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerInfo/getByKeywords",
        "resourceBos": []
      },
      {
        "code": "insurance_partner_detail",
        "id": 54965,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "查看合作方详情",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerInfo/getDetail",
        "resourceBos": []
      },
      {
        "code": "insurance_partner_add",
        "id": 54966,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "新增合作方",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerlInfo/insert",
        "resourceBos": []
      },
      {
        "code": "insurance_partner_modify",
        "id": 54967,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改合作方备注",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerInfo/updateRemark",
        "resourceBos": []
      },
      {
        "code": "insurance_partner_reset",
        "id": 54968,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "重置合作方密钥",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerInfo/updatePartnerSec",
        "resourceBos": []
      },
      {
        "code": "insurance_partner_update",
        "id": 54969,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "修改合作方状态",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerInfo/updatePartnerStatus",
        "resourceBos": []
      },
      {
        "code": "insurance_partner_getListByNoAndName",
        "id": 54970,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 0,
        "name": "条件查询合作方",
        "parentId": 54963,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "http://oper.tongbb.net/basePartnerInfo/listPartnerNoAndName",
        "resourceBos": []
      }
    ]
  },
  {
    "code": "insurance_correction",
    "id": 54988,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "批改管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "https://oper.tongbb.net/insurance/correction",
    "resourceBos": [
      {
        "code": "insurance_correction_approval",
        "id": 54989,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "批改审核",
        "parentId": 54988,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/correction/approval",
        "resourceBos": [
          {
            "code": "insurance_correct_query_detail",
            "id": 54991,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "批改单详情查询",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/query/detail",
            "resourceBos": []
          },
          {
            "code": "insurance_correct_task_list",
            "id": 54992,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "批改单任务池",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/task/list",
            "resourceBos": []
          },
          {
            "code": "insurance_correct_get_task",
            "id": 54993,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "批改单领取任务",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/get/task",
            "resourceBos": []
          },
          {
            "code": "insurance_media_upload",
            "id": 54994,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "图片上传",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/media/upload",
            "resourceBos": []
          },
          {
            "code": "insurance_media_download",
            "id": 54995,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "图片下载",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/media/download",
            "resourceBos": []
          },
          {
            "code": "insurance_correct_own_task_list",
            "id": 54996,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "个人任务",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/own/task/list",
            "resourceBos": []
          },
          {
            "code": "insurance_driving_student_operate_add",
            "id": 54997,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "单个学员信息处理",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/driving/student/operate/add",
            "resourceBos": []
          },
          {
            "code": "insurance_driving_student_operate_detail",
            "id": 54998,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "单个学员信息详情",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/driving/student/operate/detail",
            "resourceBos": []
          },
          {
            "code": "insurance_policy_correct_commit",
            "id": 55000,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "批改操作提交",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/commit",
            "resourceBos": []
          },
          {
            "code": "insurance_correct_approval_page",
            "id": 55061,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 1,
            "name": "批改详情",
            "parentId": 54989,
            "position": null,
            "visible": false,
            "status": 0,
            "url": "https://oper.tongbb.net/insurance/correction/approvalPage",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_correction_query",
        "id": 54990,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "批改查询",
        "parentId": 54988,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/correction/query",
        "resourceBos": [
          {
            "code": "insurance_correct_query_list",
            "id": 54999,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "批改列表",
            "parentId": 54990,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/query/list",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_correction_approval_page",
        "id": 55075,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 1,
        "name": "批改详情处理页面",
        "parentId": 54988,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/correction/approvalPage",
        "resourceBos": [
          {
            "code": "policy_correct_query_detail",
            "id": 55076,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "批改详情查询",
            "parentId": 55075,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/correct/query/detail",
            "resourceBos": []
          }
        ]
      }
    ]
  },
  {
    "code": "insurance_compensate",
    "id": 55062,
    "description": "",
    "level": 1,
    "menu": true,
    "moduleType": 2,
    "name": "理赔管理",
    "parentId": 0,
    "position": null,
    "visible": false,
    "status": 1,
    "url": "https://oper.tongbb.net/insurance/compensate",
    "resourceBos": [
      {
        "code": "insurance_compensate_approval",
        "id": 55063,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "理赔审核",
        "parentId": 55062,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/compensate/approval",
        "resourceBos": [
          {
            "code": "insurance_compensate_task_list",
            "id": 55066,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "理赔列表",
            "parentId": 55063,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/claim/task/list",
            "resourceBos": []
          },
          {
            "code": "insurance_compensate_get_task",
            "id": 55067,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "领取任务",
            "parentId": 55063,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/claim/get/task",
            "resourceBos": []
          },
          {
            "code": "insurance_compensate_commit",
            "id": 55068,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "理赔审核提交",
            "parentId": 55063,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/claim/commit",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_compensate_query",
        "id": 55064,
        "description": "",
        "level": 2,
        "menu": true,
        "moduleType": 1,
        "name": "理赔查询",
        "parentId": 55062,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/compensate/query",
        "resourceBos": [
          {
            "code": "insurance_compensate_query_list",
            "id": 55069,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "理赔查询列表",
            "parentId": 55064,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/claim/query/list",
            "resourceBos": []
          },
          {
            "code": "media_download_stream",
            "id": 55071,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "下载图片流",
            "parentId": 55064,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/media/download/stream",
            "resourceBos": []
          }
        ]
      },
      {
        "code": "insurance_compensate_approval_page",
        "id": 55077,
        "description": "",
        "level": 2,
        "menu": false,
        "moduleType": 1,
        "name": "理赔详情处理",
        "parentId": 55062,
        "position": null,
        "visible": false,
        "status": 1,
        "url": "https://oper.tongbb.net/insurance/compensate/approvalPage",
        "resourceBos": [
          {
            "code": "policy_claim_query_detail",
            "id": 55078,
            "description": "",
            "level": 3,
            "menu": false,
            "moduleType": 0,
            "name": "理赔详情接口",
            "parentId": 55077,
            "position": null,
            "visible": false,
            "status": 1,
            "url": "https://oper.tongbb.net/policy/claim/query/detail",
            "resourceBos": []
          }
        ]
      }
    ]
  }
]
